#---------------------------------------------------------------------
# Archivo de configuracion clamd.conf
#---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: clamav-config
  namespace: nextcloud
  labels:
    app: clamav
data:
  clamd.conf: |
    # /etc/clamav/clamd.conf
    LogFile /var/log/clamav/clamd.log
    LogFileMaxSize 1048576
    LogTime yes
    PidFile /var/run/clamav/clamd.pid
    LocalSocket /run/clamav/clamd.sock
    DatabaseDirectory /var/lib/clamav
    OfficialDatabaseOnly true
    TCPSocket 3310
    TCPAddr 0.0.0.0
    User clamav
    StreamMaxLength 0
    MaxScanSize 200M
    MaxFileSize 50M
    MaxRecursion 16
    MaxFiles 100000
    AlgorithmicDetection yes
    DetectPUA yes
    HeuristicScanPrecedence yes
    ScanMail yes
    ScanArchive yes
    ScanPDF yes
    ScanOLE2 yes
    ScanSWF yes
    ScanPE yes
    ScanELF yes
    ScanHTML yes
    ScanXMLDOCS yes
    ScanHWP3 yes
    ScanPartialMessages yes
    PhishingSignatures yes
    PhishingScanURLs yes
    Bytecode yes
    BytecodeSecurity TrustSigned
    AlertBrokenExecutables yes
    AlertEncryptedArchive yes
    AlertEncryptedDoc yes
    AlertBrokenMedia yes
    AlertEncrypted yes
    AlertOLE2Macros yes
    AlertPartitionIntersection yes
    SelfCheck 300

---
#---------------------------------------------------------------------
# Archivo de configuracion freshclam.conf
#---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: freshclam-config
  namespace: nextcloud
  labels:
    app: clamav
data:
  freshclam.conf: |
    # /etc/clamav/freshclam.conf
    DatabaseDirectory /var/lib/clamav
    UpdateLogFile /var/log/clamav/freshclam.log
    LogFileMaxSize 1048576
    LogTime yes
    PidFile /var/run/clamav/freshclam.pid
    DatabaseOwner clamav
    DatabaseMirror database.clamav.net
    Checks 12
    Foreground yes
    NotifyClamd /etc/clamav/clamd.conf
    ReceiveTimeout 60
    ScriptedUpdates yes
    Bytecode yes

---
#---------------------------------------------------------------------
# Modo de publicacion de ClamAV
#---------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: clamav
  namespace: nextcloud
  labels:
    app: clamav
spec:
  type: ClusterIP
  selector:
    app: clamav
  ports:
    - port: 3310
      targetPort: 3310
      protocol: TCP

---
#---------------------------------------------------------------------
# ClamAV (Antivirus)
#---------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: nextcloud
  labels:
    app: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
      - name: clamav
        image: clamav/clamav:1.4.3
        ports:
        - name: clamd-socket
          containerPort: 3310
          protocol: TCP
        #-----------------------------------------------------------
        # Verifica si el contenedor está vivo y funcionando
        #-----------------------------------------------------------
        livenessProbe:
          tcpSocket:
            port: clamd-socket
          initialDelaySeconds: 300
          periodSeconds: 60
        #-----------------------------------------------------------
        # Verifica si el contenedor está listo para servir tráfico.
        #-----------------------------------------------------------
        readinessProbe:
          exec:
            command: ["clamdscan", "--version"]
          initialDelaySeconds: 300
          periodSeconds: 10
        #-----------------------------------------------------------
        # limites de recursos
        #-----------------------------------------------------------
        # resources:
        #   requests:
        #     cpu: "1"
        #     memory: "4Gi"
        #   limits:
        #     cpu: "1"
        #     memory: "4Gi"
        volumeMounts:
        - name: clamav-config
          mountPath: /etc/clamav/clamd.conf
          subPath: clamd.conf
        - name: freshclam-config
          mountPath: /etc/clamav/freshclam.conf
          subPath: freshclam.conf
      volumes:
      - name: clamav-config
        configMap:
          name: clamav-config
      - name: freshclam-config
        configMap:
          name: freshclam-config

---
#---------------------------------------------------------------------
# Escalado Horizontal de ClamAV
#---------------------------------------------------------------------
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: hpa-clamav
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: clamav
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: Utilization
#         averageUtilization: 80