#---------------------------------------------------------------------
# PersistentVolumeClaim para datos de Collabora
#---------------------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collabora-pvc-data
  namespace: nextcloud
  labels:
    app: collabora
spec:
  storageClassName: ceph-block
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # <--- ¡CAMBIA ESTO A TU NECESIDAD!

---
#---------------------------------------------------------------------
# Modo de publicacion de Collabora
#---------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: collabora
  namespace: nextcloud
  labels:
    app: collabora
spec:
  selector:
    app: collabora
  ports:
    - port: 9980
      targetPort: 9980
      protocol: TCP
  type: ClusterIP

---
#---------------------------------------------------------------------
# Collabora Online (CODE)
#---------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  namespace: nextcloud
  labels:
    app: collabora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      hostAliases:
      - ip: "10.43.152.50" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
      - ip: "172.16.9.10" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
        hostnames:
        - "nextcloud.test.local"  # <--- ¡CAMBIA ESTO A TU NECESIDAD!
      containers:
        - name: collabora-code
          image: collabora/code:latest
          ports:
            - containerPort: 9980
              name: collabora
          env:
            - name: aliasgroup1
              value: "https://nextcloud\\.test\\.local:443" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
            - name: server_name
              value: "collabora.local.test" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
            - name: extra_params
              value: "--o:ssl.enable=false --o:ssl.termination=true"
            - name: username
              value: "admin"
            - name: password
              valueFrom:
                secretKeyRef:
                  name: password-nextcloud
                  key: collabora_admin_password
            - name: TZ
              value: "America/Lima"
            - name: dictionaries
              value: "es_ES en_US"
          resources:
            requests:
              cpu: "1" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
              memory: "2Gi" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
            limits:
              cpu: "1" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
              memory: "2Gi" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
          securityContext:
            capabilities: { add: ["MKNOD"] }
          readinessProbe:
            httpGet: { path: /hosting/discovery, port: 9980 }
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet: { path: /hosting/discovery, port: 9980 }
            initialDelaySeconds: 180
            periodSeconds: 20
            failureThreshold: 3
          volumeMounts:
            - name: collabora-data
              mountPath: /var/lib/lool
      volumes:
        - name: collabora-data
          persistentVolumeClaim:
            claimName: collabora-pvc-data
