#---------------------------------------------------------------------
# Base de datos para Nextcloud
#---------------------------------------------------------------------
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  mariaDbRef:
    name: mariadb-galera
  characterSet: utf8
  collate: utf8_general_ci
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s

---
#---------------------------------------------------------------------
# User de Nextcloud para MariaDB
#---------------------------------------------------------------------
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  mariaDbRef:
    name: mariadb-galera
  passwordSecretKeyRef:
    name: password-nextcloud
    key: mariadb_user_password
  maxUserConnections: 50
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s


---
#---------------------------------------------------------------------
# Permisos para el usuario de Nextcloud
#---------------------------------------------------------------------
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
  namespace: nextcloud
spec:
  mariaDbRef:
    name: mariadb-galera
  privileges:
    - "ALL PRIVILEGES"
  database: "nextcloud"
  table: "*"
  username: nextcloud
  grantOption: true
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
