#-----------------------------------------------------------
# PersistentVolumeClaim para Nextcloud (apps)
#-----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # <--- ¡CAMBIA ESTO A TU NECESIDAD!

---
#-----------------------------------------------------------
# PersistentVolumeClaim para Nextcloud (data)
#-----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  storageClassName: nfs-client
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Ti # <--- ¡CAMBIA ESTO A TU NECESIDAD!

---
#---------------------------------------------------------------------
# Archivo de configuracion nextcloud.ini
#---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-php-config
  namespace: nextcloud
data:
  nextcloud.ini: |
    memory_limit = 512M
    upload_max_filesize = 30G
    post_max_size = 30G
    max_execution_time = 3600
    max_input_time = 3600
    output_buffering = Off
    date.timezone = America/Lima
    expose_php = Off

  opcache-recommended.ini: |
    opcache.enable=1
    opcache.interned_strings_buffer=64M
    opcache.max_accelerated_files=20000
    opcache.memory_consumption=512M
    opcache.save_comments=1
    opcache.revalidate_freq=60
    opcache.jit=1255
    opcache.jit_buffer_size=32M
    opcache.validate_timestamps=1
    opcache.fast_shutdown=1
    opcache.enable_cli=1

  www.conf: |
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    pm = dynamic
    pm.max_children = 60
    pm.start_servers = 30
    pm.min_spare_servers = 30
    pm.max_spare_servers = 40
    
---
#-----------------------------------------------------------
# Modo de publicacion de Nextcloud
#-----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud  
spec:
  type: ClusterIP
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
#-----------------------------------------------------------
# Nextcloud (Aplicación Principal)
#-----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:stable-apache # <--- ¡CAMBIA ESTO A TU NECESIDAD!
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "8" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
            memory: "10Gi" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
          # limits:
          #   cpu: "8"
          #   memory: "8Gi"
        ports:
          - containerPort: 80
        env:
          - name: TRUSTED_DOMAINS
            value: "nextcloud.test.local" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
          - name: OVERWRITEPROTOCOL
            value: "https"
          - name: OVERWRITEHOST
            value: "nextcloud.test.local" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
          - name: OVERWRITECLIURL
            value: "https://nextcloud.test.local" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
          - name: PHP_MAX_EXECUTION_TIME
            value: "3600"
          - name: PHP_MAX_INPUT_TIME
            value: "3600"
          - name: TZ
            value: "America/Lima"
          - name: PHP_TIMEZONE
            value: "America/Lima"
          #---------------------------------------------------------
          # Credenciales de Nextcloud
          #---------------------------------------------------------
          - name: NEXTCLOUD_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: password-nextcloud
                key: nextcloud_admin_user
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-nextcloud
                key: nextcloud_admin_password
          #---------------------------------------------------------
          # Conexion a mariadb
          #---------------------------------------------------------
          - name: MYSQL_HOST
            value: "mariadb-galera"
          - name: MYSQL_DATABASE
            value: "nextcloud"
          - name: MYSQL_USER 
            value: "nextcloud"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-nextcloud
                key: mariadb_user_password
          #---------------------------------------------------------
          # Conexion a redis
          #---------------------------------------------------------
          - name: REDIS_HOST
            value: "redis-replication-master"
          - name: REDIS_HOST_PORT
            value: "6379"
          - name: REDIS_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-nextcloud
                key: redis_password
        volumeMounts:
          - name: nextcloud
            mountPath: /var/www/html
          - name: nextcloud-data
            mountPath: /var/www/html/data
          - name: nextcloud-php-config
            mountPath: /usr/local/etc/php/conf.d/nextcloud.ini
            subPath: nextcloud.ini
          - name: nextcloud-php-config
            mountPath: /usr/local/etc/php/conf.d/opcache-recommended.ini
            subPath: opcache-recommended.ini
          - name: nextcloud-php-config
            mountPath: /usr/local/etc/php-fpm.d/www.conf
            subPath: www.conf
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - name: nextcloud-php-config
          configMap:
            name: nextcloud-php-config
