#-----------------------------------------------------------
# PersistentVolumeClaim para Nextcloud (apps)
#-----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  storageClassName: longhorn # <--- ¡CAMBIA ESTO A TU NECESIDAD!
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # <--- ¡CAMBIA ESTO A TU NECESIDAD!

---
#-----------------------------------------------------------
# PersistentVolumeClaim para Nextcloud (data)
#-----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  storageClassName: nfs-client # <--- ¡CAMBIA ESTO A TU NECESIDAD!
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Ti # <--- ¡CAMBIA ESTO A TU NECESIDAD!

---
#---------------------------------------------------------------------
# Archivo de configuracion nextcloud.ini
#---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-php-config
  namespace: nextcloud
data:
  nextcloud.ini: |
    memory_limit = 512M
    upload_max_filesize = 30G
    post_max_size = 30G
    max_execution_time = 3600
    max_input_time = 3600
    output_buffering = Off
    date.timezone = America/Lima

  opcache-recommended.ini: |
    opcache.enable=1
    opcache.interned_strings_buffer=64M
    opcache.max_accelerated_files=20000
    opcache.memory_consumption=256M
    opcache.save_comments=1
    opcache.revalidate_freq=60
    opcache.jit=1255
    opcache.jit_buffer_size=32M
    opcache.validate_timestamps=1
    opcache.fast_shutdown=1
    opcache.enable_cli=1

  www.conf: |
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    pm = dynamic
    pm.max_children = 16
    pm.start_servers = 4
    pm.min_spare_servers = 2
    pm.max_spare_servers = 8
    pm.max_requests = 500
    slowlog = /var/log/php-fpm/www-slow.log
    request_slowlog_timeout = 30s
    request_terminate_timeout = 300s
    rlimit_files = 1024
    catch_workers_output = yes
    clear_env = no
    security.limit_extensions = .php .php3 .php4 .php5 .phtml
    php_admin_value = 512M
    php_admin_value = /var/log/php-fpm/www-error.log
    php_admin_flag = on

---
#-----------------------------------------------------------
# Modo de publicacion de Nextcloud
#-----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud  
spec:
  type: ClusterIP
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
#-----------------------------------------------------------
# Nextcloud (Aplicación Principal)
#-----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1 # <--- ¡CAMBIA ESTO A TU NECESIDAD!
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      initContainers:
        #-----------------------------------------------------------
        # Verificacion de conexion a postgresql
        #-----------------------------------------------------------
      - name: wait-for-mariadb-cluster
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z mariadb-galera 3306; do echo waiting for mariadb; sleep 2; done;']
        #-----------------------------------------------------------
        # Verificacion de conexion a redis
        #-----------------------------------------------------------
      - name: wait-for-redis-cluster
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z redis-replication-master 6379; do echo waiting for redis; sleep 2; done;']
      containers:
      - name: nextcloud
        image: nextcloud:stable-apache
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "4" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
            memory: "8Gi" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
          limits:
            cpu: "4" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
            memory: "8Gi" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
        ports:
          - containerPort: 80
        env:
          - name: TRUSTED_DOMAINS
            value: "domain.test.com" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
          - name: OVERWRITEPROTOCOL
            value: "https"
          - name: OVERWRITEHOST
            value: "domain.test.com" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
          - name: OVERWRITECLIURL
            value: "https://domain.test.com" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
          - name: PHP_MAX_EXECUTION_TIME
            value: "3600"
          - name: PHP_MAX_INPUT_TIME
            value: "3600"
          - name: TZ
            value: "America/Lima"
          - name: PHP_TIMEZONE
            value: "America/Lima"
          #---------------------------------------------------------
          # Credenciales de Nextcloud
          #---------------------------------------------------------
          - name: NEXTCLOUD_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: password-nextcloud
                key: nextcloud_admin_user
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-nextcloud
                key: nextcloud_admin_password
          #---------------------------------------------------------
          # Conexion a mariadb
          #---------------------------------------------------------
          - name: MYSQL_HOST
            value: "mariadb-galera"
          - name: MYSQL_DATABASE
            value: "nextcloud"
          - name: MYSQL_USER 
            value: "nextcloud"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-nextcloud
                key: mariadb_user_password
          #---------------------------------------------------------
          # Conexion a redis
          #---------------------------------------------------------
          - name: REDIS_HOST
            value: "redis-replication-master"
          - name: REDIS_HOST_PORT
            value: "6379"
          - name: REDIS_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-nextcloud
                key: redis_password
        volumeMounts:
          - name: nextcloud
            mountPath: /var/www/html
          - name: nextcloud-data
            mountPath: /var/www/html/data
          - name: nextcloud-php-config
            mountPath: /usr/local/etc/php/conf.d/nextcloud.ini
            subPath: nextcloud.ini
          - name: nextcloud-php-config
            mountPath: /usr/local/etc/php/conf.d/opcache-recommended.ini
            subPath: opcache-recommended.ini
          - name: nextcloud-php-config
            mountPath: /usr/local/etc/php-fpm.d/www.conf
            subPath: www.conf
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - name: nextcloud-php-config
          configMap:
            name: nextcloud-php-config

---
#---------------------------------------------------------------------
# Escalado Horizontal de Nextcloud
#---------------------------------------------------------------------
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nextcloud
  namespace: nextcloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextcloud
  minReplicas: 1 # <--- ¡CAMBIA ESTO A TU NECESIDAD!
  maxReplicas: 3 # <--- ¡CAMBIA ESTO A TU NECESIDAD!
  metrics:
  - type: Resource
    resource:
      name: cpu # <--- ¡CAMBIA ESTO A TU NECESIDAD!
      target:
        type: Utilization
        averageUtilization: 50 # <--- ¡CAMBIA ESTO A TU NECESIDAD!
