# Archivo de configuración para ClamAV
apiVersion: v1
kind: ConfigMap
metadata:
  name: clamav-config
data:
  # Configuración para el demonio clamd.
  # Escuchará en todas las interfaces (0.0.0.0) en el puerto TCP 3310.
  clamd.conf: |
    # /etc/clamav/clamd.conf
    LogFile /var/log/clamav/clamd.log
    LogFileMaxSize 1048576
    LogTime yes
    PidFile /var/run/clamav/clamd.pid
    LocalSocket /run/clamav/clamd.sock
    DatabaseDirectory /var/lib/clamav
    OfficialDatabaseOnly true
    TCPSocket 3310
    TCPAddr 0.0.0.0
    User clamav
    StreamMaxLength 0
    MaxScanSize 200M
    MaxFileSize 50M
    MaxRecursion 16
    MaxFiles 100000
    ArchiveMaxRecursion 10
    AlgorithmicDetection yes
    DetectPUA yes
    HeuristicScanPrecedence yes
    ScanMail yes
    ScanArchive yes
    ScanPDF yes
    ScanOLE2 yes
    ScanSWF yes
    ScanPE yes
    ScanELF yes
    ScanHTML yes
    ScanXMLDOCS yes
    ScanHWP3 yes
    ScanPartialMessages yes
    PhishingSignatures yes
    PhishingScanURLs yes
    Bytecode yes
    BytecodeSecurity TrustSigned
    AlertBrokenExecutables yes
    AlertEncryptedArchive yes
    AlertEncryptedDoc yes
    AlertBrokenMedia yes
    AlertEncrypted yes
    AlertOLE2Macros yes
    AlertPartitionIntersection yes
    SelfCheck 300

---
# Despliegue de la aplicación ClamAV
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  labels:
    app: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
      - name: clamav
        image: clamav/clamav:1.4.3
        ports:
        - name: clamd-tcp
          containerPort: 3310
          protocol: TCP
        # Montar la configuración y el volumen para la base de datos de virus.
        volumeMounts:
        - name: clamav-db
          mountPath: /var/lib/clamav
        - name: clamav-config-volume
          mountPath: /etc/clamav/clamd.conf
          subPath: clamd.conf # Monta solo este archivo del ConfigMap
        - name: clamav-logs
          mountPath: /var/log/clamav
        # Probes para que Kubernetes sepa si el servicio está listo y saludable.
        # readinessProbe:
        #   tcpSocket:
        #     port: clamd-tcp
        #   initialDelaySeconds: 60 # Espera a que se descargue la BBDD inicial
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: clamd-tcp
        #   initialDelaySeconds: 120
        #   periodSeconds: 30
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
      volumes:
      - name: clamav-db
        emptyDir: {}
      - name: clamav-config-volume
        configMap:
          name: clamav-config
      - name: clamav-logs
        emptyDir: {}

---
# Servicio para exponer ClamAV a otras pods
apiVersion: v1
kind: Service
metadata:
  name: clamav
spec:
  type: ClusterIP
  selector:
    app: clamav
  ports:
    - port: 3310        # El puerto en el que el servicio escuchará.
      targetPort: 3310 # El puerto en el pod al que se redirigirá el tráfico.
      protocol: TCP
