apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cron
  labels:
    app: nextcloud
spec:
  schedule: "*/5 * * * *" # Ejecutar cada 5 minutos
  successfulJobsHistoryLimit: 1 # Mantener solo 1 Job exitoso
  failedJobsHistoryLimit: 1 # Mantener solo 1 Job fallido   
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 33 
            runAsNonRoot: true 
            runAsUser: 33 
            runAsGroup: 33 
          containers:
          - name: nextcloud-cron
            image: nextcloud:31.0.6-apache # Asegúrate de usar la misma imagen que tu Nextcloud
            command: ["php", "-f", "/var/www/html/cron.php"]
            volumeMounts:
            - name: nextcloud
              mountPath: /var/www/html 
            - name: nextcloud-data
              mountPath: /var/www/html/data 
            - name: nextcloud-config
              mountPath: /var/www/html/config 
            - name: nextcloud-apps
              mountPath: /var/www/html/custom_apps 
            envFrom:
            - secretRef:
                name: password-nextcloud # <--- ¡ASEGURATE QUE SEA TU SECRET!
          restartPolicy: OnFailure
          volumes:
            - name: nextcloud
              persistentVolumeClaim:
                claimName: nextcloud
            - name: nextcloud-data
              persistentVolumeClaim:
                claimName: nextcloud-data 
            - name: nextcloud-config
              persistentVolumeClaim:
                claimName: nextcloud-config
            - name: nextcloud-apps
              persistentVolumeClaim:
                claimName: nextcloud-apps
