apiVersion: batch/v1
kind: Job
metadata:
  name: nextcloud-db-repair-job
  labels:
    app: nextcloud
spec:
  template:
    spec:
      restartPolicy: OnFailure # Mantiene el pod en caso de fallo
      containers:
      - name: db-repairer
        image: nextcloud:31.0.6-apache # Asegúrate de usar la misma imagen que tu Nextcloud
        command: ["sh", "-c"] 
        args:
          - |
            # --- COPIA LOS COMANDOS OCC DE LA BASE DE DATOS AQUÍ ---
            CONFIG_FILE="/var/www/html/config/config.php"
            NEXTCLOUD_PATH="/var/www/html"
            OCC_COMMAND="php ${NEXTCLOUD_PATH}/occ"

            echo "Esperando que el archivo config.php de Nextcloud esté disponible..."
            # Asegúrate de que el archivo config.php existe antes de intentar modificarlo
            ATTEMPTS=0
            MAX_ATTEMPTS=30
            while [ ! -f "$CONFIG_FILE" ] && [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
                echo "config.php no encontrado aún, esperando..."
                sleep 5
                ATTEMPTS=$((ATTEMPTS+1))
            done

            if [ ! -f "$CONFIG_FILE" ]; then
                echo "Error: config.php no fue encontrado después de múltiples intentos. Saliendo.."
                exit 1
            fi

            # --- INICIA MODO MANTENIMIENTO ---
            echo "Activando el modo de mantenimiento de Nextcloud..."
            su -s /bin/bash www-data -c "cd ${NEXTCLOUD_PATH} && ${OCC_COMMAND} maintenance:mode --on"

            echo "Ajustar el inicio de la ventana de mantenimiento..."
            su -s /bin/bash www-data -c "cd ${NEXTCLOUD_PATH} && ${OCC_COMMAND} config:system:set maintenance_window_start --type=integer --value=1"

            echo "Ejecutar maintenance:repair --include-expensive..."
            su -s /bin/bash www-data -c "cd ${NEXTCLOUD_PATH} && ${OCC_COMMAND} maintenance:repair --include-expensive"

            echo "Ejecutar db:add-missing-columns..."
            su -s /bin/bash www-data -c "cd ${NEXTCLOUD_PATH} && ${OCC_COMMAND} db:add-missing-columns"

            echo "Ejecutar db:add-missing-indices..."
            su -s /bin/bash www-data -c "cd ${NEXTCLOUD_PATH} && ${OCC_COMMAND} db:add-missing-indices"

            echo "Ejecutar db:add-missing-primary-keys..."
            su -s /bin/bash www-data -c "cd ${NEXTCLOUD_PATH} && ${OCC_COMMAND} db:add-missing-primary-keys"

            echo "Borrando la caché de Nextcloud..."
            su -s /bin/bash www-data -c "cd ${NEXTCLOUD_PATH} && ${OCC_COMMAND} memcache:redis:command FLUSHALL"

            # --- FIN MODO MANTENIMIENTO ---
            echo "Comandos de reparación de base de datos finalizados."
            echo "Desactivando el modo de mantenimiento de Nextcloud..."
            su -s /bin/bash www-data -c "cd ${NEXTCLOUD_PATH} && ${OCC_COMMAND} maintenance:mode --off"
        envFrom:
          - secretRef:
              name: password-nextcloud
        volumeMounts:
          - name: nextcloud
            mountPath: /var/www/html
          - name: nextcloud-data
            mountPath: /var/www/html/data
          - name: nextcloud-config
            mountPath: /var/www/html/config
          - name: nextcloud-apps
            mountPath: /var/www/html/custom_apps
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - name: nextcloud-config
          persistentVolumeClaim:
            claimName: nextcloud-config
        - name: nextcloud-apps
          persistentVolumeClaim:
            claimName: nextcloud-apps
