apiVersion: batch/v1
kind: Job
metadata:
  name: nextcloud-set-cookie-same-site-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 33 
        runAsUser: 33 
      containers:
      - name: config-updater
        image: nextcloud:31.0.6-apache
        command: ["sh", "-c"]
        args:
          - |
            CONFIG_FILE="/var/www/html/config/config.php"
            COOKIE_SAME_SITE_VALUE="Lax" # <--- Puedes cambiar esto a "Strict" si lo necesitas

            if grep -q "'cookie_same_site'" "$CONFIG_FILE"; then
                sed -i "/'cookie_same_site'/c\ 'cookie_same_site' => '${COOKIE_SAME_SITE_VALUE}'," "$CONFIG_FILE"
            else
                sed -i "/);/i \  'cookie_same_site' => '${COOKIE_SAME_SITE_VALUE}'," "$CONFIG_FILE"
            fi
        volumeMounts:
          - name: nextcloud-config 
            mountPath: /var/www/html/config
      volumes:
        - name: nextcloud-config
          persistentVolumeClaim:
            claimName: nextcloud-config 
