apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup-nfs
  namespace: nextcloud
spec:
  mariaDbRef:
    name: mariadb-galera
  schedule:
    cron: "30 3 * * *" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
    suspend: false
  timeZone: "UTC"
  maxRetention: 720h
  compression: bzip2
  storage:
    volume:
      nfs:
        server: 192.168.1.1 # <--- ¡CAMBIA ESTO A TU NECESIDAD!
        path: /DATA_STORAGE # <--- ¡CAMBIA ESTO A TU NECESIDAD!
