#---------------------------------------------------------------------
# PersistentVolumeClaim para datos de Collabora
#---------------------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collabora-pvc-data
  labels:
    app: collabora
spec:
  #storageClassName: nfs-client # <--- ¡DESCOMENTA ESO SI USAS ALMACENAMIENTO NFS!
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
#---------------------------------------------------------------------
# Modo de publicacion de Collabora
#---------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: collabora
spec:
  selector:
    app: collabora
  ports:
    - port: 9980
      targetPort: 9980
      protocol: TCP
  type: ClusterIP 

---
#---------------------------------------------------------------------
# Collabora Online (CODE)
#---------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  labels:
    app: collabora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      containers:
        - name: collabora-code
          image: collabora/code:latest
          ports:
            - containerPort: 9980
              name: collabora
          env:
            - name: dictionaries
              value: "es_ES en_US"
            - name: timezone
              value: "America/Lima"
            - name: extra_params
              value: "--o:ssl.enable=false --o:ssl.termination=true --o:host_url=https://localhost.test/" # <--- ¡CAMBIA ESTO A TU DOMINIO DE NEXTCLOUD!
            - name: username
              value: "admin" # <--- ¡USUARIO DE ADMINISTRACION!
            - name: password
              valueFrom:
                secretKeyRef:
                  name: password-nextcloud
                  key: collabora_admin_password # <--- ¡ASEGURATE QUE SEA TU SECRET!
            - name: domain
              value: "localhost.test"  # <--- ¡CAMBIA ESTO A TU DOMINIO DE COLLABORA!
            - name: TZ
              value: "America/Lima"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          securityContext:
            capabilities: { add: ["MKNOD"] }
          readinessProbe:
            httpGet: { path: /hosting/discovery, port: 9980 }
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet: { path: /hosting/discovery, port: 9980 }
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          volumeMounts:
            - name: collabora-data
              mountPath: /var/lib/lool
      volumes:
        - name: collabora-data
          persistentVolumeClaim:
            claimName: collabora-pvc-data
