#-----------------------------------------------------------
# PersistentVolumeClaim para Nextcloud
#-----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  #storageClassName: nfs-client # <--- ¡DESCOMENTA ESO SI USAS ALMACENAMIENTO NFS!
  accessModes:
    - ReadWriteOnce #Many
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi

---
#-----------------------------------------------------------
# PersistentVolumeClaim para Configuracion de Nextcloud
#-----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  labels:
    app: nextcloud
spec:
  #storageClassName: nfs-client # <--- ¡DESCOMENTA ESO SI USAS ALMACENAMIENTO NFS!
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
#-----------------------------------------------------------
# PersistentVolumeClaim para Datos de PHP
#-----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  labels:
    app: nextcloud
spec:
  #storageClassName: nfs-client # <--- ¡DESCOMENTA ESO SI USAS ALMACENAMIENTO NFS!
  accessModes:
    - ReadWriteOnce #Many
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi

---
#-----------------------------------------------------------
# PersistentVolumeClaim para apps de Nextcloud
#-----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-apps
  labels:
    app: nextcloud
spec:
  #storageClassName: nfs-client # <--- ¡DESCOMENTA ESO SI USAS ALMACENAMIENTO NFS!
  accessModes:
    - ReadWriteOnce #Many
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi

---
#-----------------------------------------------------------
# Modo de publicacion de Nextcloud
#-----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud  
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nextcloud

---
#-----------------------------------------------------------
# Nextcloud (Aplicación Principal)
#-----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: default
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      initContainers:
          #-----------------------------------------------------------
          # Verificacion de conexion a mariadb
          #-----------------------------------------------------------
        - name: wait-for-mariadb
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mariadb 3306; do echo waiting for mariadb; sleep 2; done;']
          #-----------------------------------------------------------
          # Verificacion de conexion a redis
          #-----------------------------------------------------------
        - name: wait-for-redis
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: nextcloud
          image: nextcloud:31.0.6-apache
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 
          env:
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "localhost.test 127.0.0.1" # <--- ¡CAMBIA ESTO A TU DOMINIO!
            - name: NO_PROXY
              value: "localhost,127.0.0.1,nextcloud,10.0.0.0/8,192.168.0.0/16,.svc,.cluster.local"  # <--- ¡CAMBIA ESTO A TUS REDES O EQUIPOS QUE NO ESTAN EN EL PROXY!
            - name: NEXTCLOUD_OVERWRITEPROTOCOL
              value: "https"
            - name: NEXTCLOUD_OVERWRITEHOST
              value: "localhost.test" # <--- ¡CAMBIA ESTO A TU DOMINIO!
            - name: NEXTCLOUD_OVERWRITECLIURL
              value: "https://localhost.test" # <--- ¡CAMBIA ESTO A TU DOMINIO!
            - name: PHP_OPCACHE_MEMORY_LIMIT 
              value: "2480M"
            - name: PHP_MEMORY_LIMIT 
              value: "1024M"
            - name: PHP_UPLOAD_LIMIT
              value: "10G"
            - name: PHP_MAX_EXECUTION_TIME
              value: "3600"
            - name: PHP_MAX_INPUT_TIME
              value: "3600"
            #---------------------------------------------------------
            # Conexion a mariadb
            #---------------------------------------------------------
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: password-nextcloud # <--- ¡ASEGURATE QUE SEA TU SECRET!
                  key: mariadb_database 
            - name: MYSQL_USER 
              valueFrom:
                secretKeyRef:
                  name: password-nextcloud # <--- ¡ASEGURATE QUE SEA TU SECRET!
                  key: mariadb_user 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: password-nextcloud # <--- ¡ASEGURATE QUE SEA TU SECRET!
                  key: mariadb_password
            #---------------------------------------------------------
            # Conexion a redis
            #---------------------------------------------------------
            - name: REDIS_HOST
              value: "redis" 
            - name: REDIS_PORT
              value: "6379" 
            - name: REDIS_HOST_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: password-nextcloud # <--- ¡ASEGURATE QUE SEA TU SECRET!
                  key: redis_password
          #-----------------------------------------------------------
          # limites de recursos
          #-----------------------------------------------------------
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: nextcloud
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/html/data
            - name: nextcloud-config
              mountPath: /var/www/html/config
            - name: nextcloud-apps
              mountPath: /var/www/html/custom_apps
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - name: nextcloud-config
          persistentVolumeClaim:
            claimName: nextcloud-config
        - name: nextcloud-apps
          persistentVolumeClaim:
            claimName: nextcloud-apps
