#------------------------------------------------------------
# Secrets
# Codifica tus contraseñas en Base64 antes de ponerlas aquí:
# echo -n 'tu_contraseña' | base64
#------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: password-nextcloud
type: Opaque
data:
#-----------------------------------------------------------
# Contraseñas para MariaDB 
#-----------------------------------------------------------
  mariadb_root_password: "cm9vdHBhc3N3b3Jk" #rootpassword
  mariadb_password: "bmV4dGNsb3VkcGFzc3dvcmQ=" #nextcloudpassword
  mariadb_database: "bmV4dGNsb3Vk" #nextcloud
  mariadb_user: "bmV4dGNsb3Vk" #nextcloud
#-----------------------------------------------------------
# Contraseña para Redis 
#-----------------------------------------------------------
  redis_password: "cmVkaXM=" #redis
#-----------------------------------------------------------
# Contraseña para admin de Collabora 
#-----------------------------------------------------------
  collabora_admin_password: "Y29sbGFib3Jh" #collabora
