apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-collabora 
spec:
  acme:
    email: tu-email@example.com # <--- ¡CAMBIA ESTO A TU CORREO ELECTRONICO!
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-private-key 
    solvers:
    - http01:
        ingress:
          class: nginx
