#-----------------------------------------------------------
# MariaDB Backup via NFS
#-----------------------------------------------------------
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup-nfs-nextcloud
  namespace: nextcloud
spec:
  mariaDbRef:
    name: mariadb-galera
  schedule:
    cron: "30 3 * * *" # <--- ¡CAMBIA ESTO A TU NECESIDAD!
    suspend: false
  timeZone: "UTC"
  maxRetention: 720h # <--- ¡CAMBIA ESTO A TU NECESIDAD!
  compression: bzip2
  storage:
    volume:
      nfs:
        server: 192.168.52.191 # <--- ¡CAMBIA ESTO A TU NECESIDAD!
        path: /NFS # <--- ¡CAMBIA ESTO A TU NECESIDAD!
